# Generated by Django 5.1 on 2024-08-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parking_images/')),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
