# Generated by Django 5.1 on 2024-08-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0002_parkingimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("track", "Track"),
                            ("car", "Car"),
                            ("motorcycle", "Motorcycle"),
                            ("yaht", "Yacht"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rate_per_hour", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
