# Generated by Django 5.1 on 2024-08-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0003_parkingrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(default="car", max_length=20),
        ),
    ]
